$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)
require "minitest/autorun"

require "trailblazer/macro"
require "trailblazer/developer"
require "trailblazer/core"

T = Trailblazer::Core

require "trailblazer/invoke/activity" # adds {Railway.__}.

Memo = Struct.new(:id, :body) do
  def self.find(id)
    return new(id, "Yo!") if id
    nil
  end
end

module Rehash
  def rehash(ctx, seq:, rehash_raise: false, **)
    seq << :rehash
    raise rehash_raise if rehash_raise
    true
  end
end

Minitest::Spec.include Trailblazer::Core::Utils::Assertions

Minitest::Spec.class_eval do
  def trace(activity, ctx)
    signal, (ctx, flow_options) = Trailblazer::Activity::Railway.__(activity, ctx, **Trailblazer::Developer::Trace.options_for_canonical_invoke)

    stack = flow_options[:stack]

    output = Trailblazer::Developer::Trace::Present.(stack) do |trace_nodes:, **|
      {node_options: {trace_nodes[0] => {label: "TOP"}}}
    end.gsub(/:\d+/, "")

    return output, signal, ctx
  end

  def assert_equal(asserted, expected, *args)
    super(expected, asserted, *args)
  end
end

# Uncomment me when changing tests!
# Trailblazer::Core.convert_operation_test("test/docs/model_find_test.rb", target: "test/docs/autogenerated/operation_model_find_test.rb", source_gem: "trailblazer-macro")
# Trailblazer::Core.convert_operation_test("test/docs/each_test.rb", target: "test/docs/autogenerated/operation_each_test.rb", source_gem: "trailblazer-macro")
# Trailblazer::Core.convert_operation_test("test/docs/model_test.rb", target: "test/docs/autogenerated/operation_model_test.rb", source_gem: "trailblazer-macro")
