inherit_from:
  - https://raw.githubusercontent.com/trailblazer/meta/master/rubocop.yml
  - .rubocop_todo.yml

Style/StringLiterals:
  EnforcedStyle: double_quotes

Naming/MethodName:
  Exclude:
    - 'test/docs/macro_test.rb'
    - 'lib/trailblazer/operation/model.rb'
    - 'lib/trailblazer/operation/wrap.rb'
    - 'lib/trailblazer/operation/pundit.rb'
    - 'lib/trailblazer/operation/rescue.rb'
    - 'lib/trailblazer/operation/nested.rb'
    - 'lib/trailblazer/operation/guard.rb'
    - 'lib/trailblazer/operation/wrap.rb'
    - 'lib/trailblazer/operation/policy.rb'
