require "bundler/gem_tasks"
require "rake/testtask"

Rake::TestTask.new(:test) do |test|
  test.libs << 'test'
  test.test_files = FileList['test/**/*_test.rb'] - FileList['test/docs/autogenerated/*_test.rb']
  test.verbose = true
end

task default: :test
